[id="lsp-xml-vars"]
==== `lsp-xml` settings

[id="lsp-xml-trace-server"]
- `lsp-xml-trace-server`
____
Default value: `pass:["off"]`

Traces the communication between VS Code and the XML language server.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-xml-catalogs"]
- `lsp-xml-catalogs`
____
Default value: `pass:[nil]`

Array of XML Catalogs

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-xml-logs-client"]
- `lsp-xml-logs-client`
____
Default value: `pass:[t]`

Should the server log to client output

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-xml-format-split-attributes"]
- `lsp-xml-format-split-attributes`
____
Default value: `pass:[nil]`

Split multiple attributes each onto a new line

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-xml-format-join-cdata-lines"]
- `lsp-xml-format-join-cdata-lines`
____
Default value: `pass:[nil]`

Join lines in a CDATA tag’s content

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-xml-format-join-comment-lines"]
- `lsp-xml-format-join-comment-lines`
____
Default value: `pass:[nil]`

Join comment content on format

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-xml-format-space-before-empty-close-tag"]
- `lsp-xml-format-space-before-empty-close-tag`
____
Default value: `pass:[t]`

Insert space before end of self closing tag.
Example: <tag/> -> <tag />

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-xml-format-join-content-lines"]
- `lsp-xml-format-join-content-lines`
____
Default value: `pass:[nil]`

Normalize the whitespace of content inside an element.
Newlines and excess whitespace are removed.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-xml-format-preserve-empty-content"]
- `lsp-xml-format-preserve-empty-content`
____
Default value: `pass:[nil]`

Preserve empty content/whitespace in a tag.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-xml-format-enabled"]
- `lsp-xml-format-enabled`
____
Default value: `pass:[t]`

Enable/disable ability to format document

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-xml-format-quotations"]
- `lsp-xml-format-quotations`
____
Default value: `pass:["doubleQuotes"]`

Which type of quotes to use for attribute values when
  formatting.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-xml-file-associations"]
- `lsp-xml-file-associations`
____
Default value: `pass:[nil]`

Allows XML schemas to be associated to file name patterns.
  Example: [{ "systemId":"path/to/file.xsd","pattern":
  "file1.xml" },{ "systemId":
  "http://www.w3.org/2001/XMLSchema.xsd","pattern":
  "**/*.xsd" }]

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-xml-completion-auto-close-tags"]
- `lsp-xml-completion-auto-close-tags`
____
Default value: `pass:[t]`

Enable/disable autoclosing of XML tags. IMPORTANT: Turn off
  editor.autoClosingTags for this to work

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-xml-server-vmargs"]
- `lsp-xml-server-vmargs`
____
Default value: `pass:["-noverify -Xmx64M\n  -XX:+UseG1GC -XX:+UseStringDeduplication"]`

Specifies extra VM
  arguments used to launch the XML Language Server. Eg. use
  ‘-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication‘ to
  bypass class verification, increase the heap size to 1GB and
  enable String deduplication with the G1 Garbage collector

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-xml-server-work-dir"]
- `lsp-xml-server-work-dir`
____
Default value: `pass:["~/.lsp4xml"]`

Set a custom folder path for cached XML Schemas. An absolute
  path is expected, although the ~ prefix (for the user home
  directory) is supported.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-xml-validation-no-grammar"]
- `lsp-xml-validation-no-grammar`
____
Default value: `pass:["hint"]`

The message severity when a document has no associated
  grammar.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-xml-validation-enabled"]
- `lsp-xml-validation-enabled`
____
Default value: `pass:[t]`

Enable/disable all validation.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-xml-validation-schema"]
- `lsp-xml-validation-schema`
____
Default value: `pass:[t]`

Enable/disable schema based validation. Ignored if
  "xml.validation.enabled": false.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-xml-jar-file"]
- `lsp-xml-jar-file`
____
Default value: `pass:["~/.emacs.d/org.eclipse.lsp4xml-0.3.0-uber.jar"]`

Xml server jar command.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-xml-server-command"]
- `lsp-xml-server-command`
____
Default value: `pass:[("java" "-jar" "~/.emacs.d/org.eclipse.lsp4xml-0.3.0-uber.jar")
]`

Xml server command.

NOTE: Introduced in `lsp-mode` 6.1

____
