(package "lsp-doc"
         "8.0.0"
         "LSP doc generator")

(website-url "https://github.com/emacs-lsp/lsp-mode")
(keywords "languages" "tool")

(package-file "lsp-doc.el")
(files "../*.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "26.1")

(development
 (depends-on "f")
 (depends-on "dash")
 (depends-on "seq")
 (depends-on "ht"))
