[id="lsp-vetur-vars"]
==== `lsp-vetur` settings

[id="lsp-vetur-use-workspace-dependencies"]
- `lsp-vetur-use-workspace-dependencies`
____
Default value: `pass:[nil]`

Use dependencies from workspace. Currently only for
TypeScript.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-completion-auto-import"]
- `lsp-vetur-completion-auto-import`
____
Default value: `pass:[t]`

Include completion for module export and auto import them

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-completion-use-scaffold-snippets"]
- `lsp-vetur-completion-use-scaffold-snippets`
____
Default value: `pass:[t]`

Enable/disable Vetur’s built-in scaffolding snippets

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-completion-tag-casing"]
- `lsp-vetur-completion-tag-casing`
____
Default value: `pass:["kebab"]`

Casing conversion for tag completion

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-grammar-custom-blocks"]
- `lsp-vetur-grammar-custom-blocks`
____
Default value: `pass:[((docs . "md")
 (i18n . "json"))
]`

Mapping from custom block tag name to language name. Used for
 generating grammar to support syntax highlighting for custom
 blocks.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-validation-template"]
- `lsp-vetur-validation-template`
____
Default value: `pass:[t]`

Validate vue-html in <template> using eslint-plugin-vue

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-validation-style"]
- `lsp-vetur-validation-style`
____
Default value: `pass:[t]`

Validate css/scss/less/postcss in <style>

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-validation-script"]
- `lsp-vetur-validation-script`
____
Default value: `pass:[t]`

Validate js/ts in <script>

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-format-enable"]
- `lsp-vetur-format-enable`
____
Default value: `pass:[t]`

Enable/disable the Vetur document formatter.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-format-options-tab-size"]
- `lsp-vetur-format-options-tab-size`
____
Default value: `pass:[2]`

Number of spaces per indentation level. Inherited by all formatters.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-format-options-use-tabs"]
- `lsp-vetur-format-options-use-tabs`
____
Default value: `pass:[nil]`

Use tabs for indentation. Inherited by all formatters.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-format-default-formatter-html"]
- `lsp-vetur-format-default-formatter-html`
____
Default value: `pass:["prettyhtml"]`

Default formatter for <template> region

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-format-default-formatter-css"]
- `lsp-vetur-format-default-formatter-css`
____
Default value: `pass:["prettier"]`

Default formatter for <style> region

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-format-default-formatter-postcss"]
- `lsp-vetur-format-default-formatter-postcss`
____
Default value: `pass:["prettier"]`

Default formatter for <style lang=’postcss’> region

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-format-default-formatter-scss"]
- `lsp-vetur-format-default-formatter-scss`
____
Default value: `pass:["prettier"]`

Default formatter for <style lang=’scss’> region

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-format-default-formatter-less"]
- `lsp-vetur-format-default-formatter-less`
____
Default value: `pass:["prettier"]`

Default formatter for <style lang=’less’> region

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-format-default-formatter-stylus"]
- `lsp-vetur-format-default-formatter-stylus`
____
Default value: `pass:["stylus-supremacy"]`

Default formatter for <style lang=’stylus’> region

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-format-default-formatter-js"]
- `lsp-vetur-format-default-formatter-js`
____
Default value: `pass:["prettier"]`

Default formatter for <script> region

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-format-default-formatter-ts"]
- `lsp-vetur-format-default-formatter-ts`
____
Default value: `pass:["prettier"]`

Default formatter for <script> region

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-format-default-formatter-options"]
- `lsp-vetur-format-default-formatter-options`
____
Default value: `pass:[((js-beautify-html
  (wrap_attributes . "force-expand-multiline"))
 (prettyhtml
  (printWidth . 100)
  (singleQuote . :json-false)
  (wrapAttributes . :json-false)
  (sortAttributes . :json-false)))
]`

Options for all default formatters

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-format-style-initial-indent"]
- `lsp-vetur-format-style-initial-indent`
____
Default value: `pass:[nil]`

Whether to have initial indent for <style> region

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-format-script-initial-indent"]
- `lsp-vetur-format-script-initial-indent`
____
Default value: `pass:[nil]`

Whether to have initial indent for <script> region

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-trace-server"]
- `lsp-vetur-trace-server`
____
Default value: `pass:["off"]`

Traces the communication between VS Code and Vue Language Server.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-tsdk"]
- `lsp-typescript-tsdk`
____
Default value: `pass:[nil]`

Specifies the folder path containing the tsserver and
lib*.d.ts files to use.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-disable-automatic-type-acquisition"]
- `lsp-typescript-disable-automatic-type-acquisition`
____
Default value: `pass:[nil]`

Disables automatic type acquisition. Automatic type
acquisition fetches ‘@types‘ packages from npm to improve
IntelliSense for external libraries.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-npm"]
- `lsp-typescript-npm`
____
Default value: `pass:[nil]`

Specifies the path to the NPM executable used for Automatic
Type Acquisition. Requires using TypeScript 2.3.4 or newer in the
workspace.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-check-npm-is-installed"]
- `lsp-typescript-check-npm-is-installed`
____
Default value: `pass:[t]`

Check if NPM is installed for Automatic Type Acquisition.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-references-code-lens-enabled"]
- `lsp-javascript-references-code-lens-enabled`
____
Default value: `pass:[nil]`

Enable/disable references CodeLens in JavaScript files.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-references-code-lens-enabled"]
- `lsp-typescript-references-code-lens-enabled`
____
Default value: `pass:[nil]`

Enable/disable references CodeLens in TypeScript files.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-implementations-code-lens-enabled"]
- `lsp-typescript-implementations-code-lens-enabled`
____
Default value: `pass:[nil]`

Enable/disable implementations CodeLens. This CodeLens shows
the implementers of an interface.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-tsserver-log"]
- `lsp-typescript-tsserver-log`
____
Default value: `pass:["off"]`

Enables logging of the TS server to a file. This log can be
used to diagnose TS Server issues. The log may contain file
paths, source code, and other potentially sensitive information
from your project.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-tsserver-plugin-paths"]
- `lsp-typescript-tsserver-plugin-paths`
____
Default value: `pass:[nil]`

Additional paths to discover Typescript Language Service
plugins. Requires using TypeScript 2.3.0 or newer in the
workspace.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-tsserver-trace"]
- `lsp-typescript-tsserver-trace`
____
Default value: `pass:["off"]`

Enables tracing of messages sent to the TS server. This trace
can be used to diagnose TS Server issues. The trace may contain
file paths, source code, and other potentially sensitive
information from your project.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-suggest-complete-function-calls"]
- `lsp-javascript-suggest-complete-function-calls`
____
Default value: `pass:[nil]`

Complete functions with their parameter signature.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-suggest-complete-function-calls"]
- `lsp-typescript-suggest-complete-function-calls`
____
Default value: `pass:[nil]`

Complete functions with their parameter signature.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-report-style-checks-as-warnings"]
- `lsp-typescript-report-style-checks-as-warnings`
____
Default value: `pass:[t]`

Report style checks as warnings.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-validate-enable"]
- `lsp-typescript-validate-enable`
____
Default value: `pass:[t]`

Enable/disable TypeScript validation.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-format-enable"]
- `lsp-typescript-format-enable`
____
Default value: `pass:[t]`

Enable/disable default TypeScript formatter.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-format-insert-space-after-comma-delimiter"]
- `lsp-typescript-format-insert-space-after-comma-delimiter`
____
Default value: `pass:[t]`

Defines space handling after a comma delimiter.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-format-insert-space-after-constructor"]
- `lsp-typescript-format-insert-space-after-constructor`
____
Default value: `pass:[nil]`

Defines space handling after the constructor keyword. Requires
using TypeScript 2.3.0 or newer in the workspace.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-format-insert-space-after-semicolon-in-for-statements"]
- `lsp-typescript-format-insert-space-after-semicolon-in-for-statements`
____
Default value: `pass:[t]`

Defines space handling after a semicolon in a for statement.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-format-insert-space-before-and-after-binary-operators"]
- `lsp-typescript-format-insert-space-before-and-after-binary-operators`
____
Default value: `pass:[t]`

Defines space handling after a binary operator.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-format-insert-space-after-keywords-in-control-flow-statements"]
- `lsp-typescript-format-insert-space-after-keywords-in-control-flow-statements`
____
Default value: `pass:[t]`

Defines space handling after keywords in a control flow
statement.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-format-insert-space-after-function-keyword-for-anonymous-functions"]
- `lsp-typescript-format-insert-space-after-function-keyword-for-anonymous-functions`
____
Default value: `pass:[t]`

Defines space handling after function keyword for anonymous
functions.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-format-insert-space-before-function-parenthesis"]
- `lsp-typescript-format-insert-space-before-function-parenthesis`
____
Default value: `pass:[nil]`

Defines space handling before function argument parentheses.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-format-insert-space-after-opening-and-before-closing-nonempty-parenthesis"]
- `lsp-typescript-format-insert-space-after-opening-and-before-closing-nonempty-parenthesis`
____
Default value: `pass:[nil]`

Defines space handling after opening and before closing
non-empty parenthesis.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-format-insert-space-after-opening-and-before-closing-nonempty-brackets"]
- `lsp-typescript-format-insert-space-after-opening-and-before-closing-nonempty-brackets`
____
Default value: `pass:[nil]`

Defines space handling after opening and before closing
non-empty brackets.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-format-insert-space-after-opening-and-before-closing-nonempty-braces"]
- `lsp-typescript-format-insert-space-after-opening-and-before-closing-nonempty-braces`
____
Default value: `pass:[t]`

Defines space handling after opening and before closing
non-empty braces. Requires using TypeScript 2.3.0 or newer in the
workspace.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-format-insert-space-after-opening-and-before-closing-template-string-braces"]
- `lsp-typescript-format-insert-space-after-opening-and-before-closing-template-string-braces`
____
Default value: `pass:[nil]`

Defines space handling after opening and before closing
template string braces.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-format-insert-space-after-opening-and-before-closing-jsx-expression-braces"]
- `lsp-typescript-format-insert-space-after-opening-and-before-closing-jsx-expression-braces`
____
Default value: `pass:[nil]`

Defines space handling after opening and before closing JSX
expression braces.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-format-insert-space-after-type-assertion"]
- `lsp-typescript-format-insert-space-after-type-assertion`
____
Default value: `pass:[nil]`

Defines space handling after type assertions in TypeScript.
Requires using TypeScript 2.4 or newer in the workspace.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-format-place-open-brace-on-new-line-for-functions"]
- `lsp-typescript-format-place-open-brace-on-new-line-for-functions`
____
Default value: `pass:[nil]`

Defines whether an open brace is put onto a new line for
functions or not.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-format-place-open-brace-on-new-line-for-control-blocks"]
- `lsp-typescript-format-place-open-brace-on-new-line-for-control-blocks`
____
Default value: `pass:[nil]`

Defines whether an open brace is put onto a new line for
control blocks or not.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-validate-enable"]
- `lsp-javascript-validate-enable`
____
Default value: `pass:[t]`

Enable/disable JavaScript validation.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-format-enable"]
- `lsp-javascript-format-enable`
____
Default value: `pass:[t]`

Enable/disable default JavaScript formatter.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-format-insert-space-after-comma-delimiter"]
- `lsp-javascript-format-insert-space-after-comma-delimiter`
____
Default value: `pass:[t]`

Defines space handling after a comma delimiter.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-format-insert-space-after-constructor"]
- `lsp-javascript-format-insert-space-after-constructor`
____
Default value: `pass:[nil]`

Defines space handling after the constructor keyword. Requires
using TypeScript 2.3.0 or newer in the workspace.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-format-insert-space-after-semicolon-in-for-statements"]
- `lsp-javascript-format-insert-space-after-semicolon-in-for-statements`
____
Default value: `pass:[t]`

Defines space handling after a semicolon in a for statement.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-format-insert-space-before-and-after-binary-operators"]
- `lsp-javascript-format-insert-space-before-and-after-binary-operators`
____
Default value: `pass:[t]`

Defines space handling after a binary operator.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-format-insert-space-after-keywords-in-control-flow-statements"]
- `lsp-javascript-format-insert-space-after-keywords-in-control-flow-statements`
____
Default value: `pass:[t]`

Defines space handling after keywords in a control flow
statement.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-format-insert-space-after-function-keyword-for-anonymous-functions"]
- `lsp-javascript-format-insert-space-after-function-keyword-for-anonymous-functions`
____
Default value: `pass:[t]`

Defines space handling after function keyword for anonymous
functions.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-format-insert-space-before-function-parenthesis"]
- `lsp-javascript-format-insert-space-before-function-parenthesis`
____
Default value: `pass:[nil]`

Defines space handling before function argument parentheses.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-format-insert-space-after-opening-and-before-closing-nonempty-parenthesis"]
- `lsp-javascript-format-insert-space-after-opening-and-before-closing-nonempty-parenthesis`
____
Default value: `pass:[nil]`

Defines space handling after opening and before closing
non-empty parenthesis.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-format-insert-space-after-opening-and-before-closing-nonempty-brackets"]
- `lsp-javascript-format-insert-space-after-opening-and-before-closing-nonempty-brackets`
____
Default value: `pass:[nil]`

Defines space handling after opening and before closing
non-empty brackets.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-format-insert-space-after-opening-and-before-closing-nonempty-braces"]
- `lsp-javascript-format-insert-space-after-opening-and-before-closing-nonempty-braces`
____
Default value: `pass:[t]`

Defines space handling after opening and before closing
non-empty braces. Requires using TypeScript 2.3.0 or newer in the
workspace.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-format-insert-space-after-opening-and-before-closing-template-string-braces"]
- `lsp-javascript-format-insert-space-after-opening-and-before-closing-template-string-braces`
____
Default value: `pass:[nil]`

Defines space handling after opening and before closing
template string braces.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-format-insert-space-after-opening-and-before-closing-jsx-expression-braces"]
- `lsp-javascript-format-insert-space-after-opening-and-before-closing-jsx-expression-braces`
____
Default value: `pass:[nil]`

Defines space handling after opening and before closing JSX
expression braces.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-format-place-open-brace-on-new-line-for-functions"]
- `lsp-javascript-format-place-open-brace-on-new-line-for-functions`
____
Default value: `pass:[nil]`

Defines whether an open brace is put onto a new line for
functions or not.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-format-place-open-brace-on-new-line-for-control-blocks"]
- `lsp-javascript-format-place-open-brace-on-new-line-for-control-blocks`
____
Default value: `pass:[nil]`

Defines whether an open brace is put onto a new line for
control blocks or not.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-implicit-project-config-check-js"]
- `lsp-javascript-implicit-project-config-check-js`
____
Default value: `pass:[nil]`

Enable/disable semantic checking of JavaScript files. Existing
jsconfig.json or tsconfig.json files override this setting.
Requires using TypeScript 2.3.1 or newer in the workspace.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-implicit-project-config-experimental-decorators"]
- `lsp-javascript-implicit-project-config-experimental-decorators`
____
Default value: `pass:[nil]`

nil

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-suggest-names"]
- `lsp-javascript-suggest-names`
____
Default value: `pass:[t]`

Enable/disable including unique names from the file in
JavaScript suggestions.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-tsc-auto-detect"]
- `lsp-typescript-tsc-auto-detect`
____
Default value: `pass:["on"]`

Controls auto detection of tsc tasks.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-suggest-paths"]
- `lsp-javascript-suggest-paths`
____
Default value: `pass:[t]`

Enable/disable suggestions for paths in import statements and
require calls.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-suggest-paths"]
- `lsp-typescript-suggest-paths`
____
Default value: `pass:[t]`

Enable/disable suggestions for paths in import statements and
require calls.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-suggest-auto-imports"]
- `lsp-javascript-suggest-auto-imports`
____
Default value: `pass:[t]`

Enable/disable auto import suggestions. Requires using
TypeScript 2.6.1 or newer in the workspace.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-suggest-auto-imports"]
- `lsp-typescript-suggest-auto-imports`
____
Default value: `pass:[t]`

Enable/disable auto import suggestions. Requires using
TypeScript 2.6.1 or newer in the workspace.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-suggest-complete-js-docs"]
- `lsp-javascript-suggest-complete-js-docs`
____
Default value: `pass:[t]`

Enable/disable suggestion to complete JSDoc comments.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-suggest-complete-js-docs"]
- `lsp-typescript-suggest-complete-js-docs`
____
Default value: `pass:[t]`

Enable/disable suggestion to complete JSDoc comments.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-locale"]
- `lsp-typescript-locale`
____
Default value: `pass:[nil]`

nil

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-suggestion-actions-enabled"]
- `lsp-javascript-suggestion-actions-enabled`
____
Default value: `pass:[t]`

Enable/disable suggestion diagnostics for JavaScript files in
the editor. Requires using TypeScript 2.8 or newer in the
workspace.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-suggestion-actions-enabled"]
- `lsp-typescript-suggestion-actions-enabled`
____
Default value: `pass:[t]`

Enable/disable suggestion diagnostics for TypeScript files in
the editor. Requires using TypeScript 2.8 or newer in the
workspace.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-preferences-quote-style"]
- `lsp-javascript-preferences-quote-style`
____
Default value: `pass:["auto"]`

nil

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-preferences-quote-style"]
- `lsp-typescript-preferences-quote-style`
____
Default value: `pass:["auto"]`

nil

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-preferences-import-module-specifier"]
- `lsp-javascript-preferences-import-module-specifier`
____
Default value: `pass:["auto"]`

Preferred path style for auto imports.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-preferences-import-module-specifier"]
- `lsp-typescript-preferences-import-module-specifier`
____
Default value: `pass:["auto"]`

Infer the shortest path type.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-preferences-rename-shorthand-properties"]
- `lsp-javascript-preferences-rename-shorthand-properties`
____
Default value: `pass:[t]`

Enable/disable introducing aliases for object shorthand
properties during renames. Requires using TypeScript 3.4 or newer
in the workspace.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-preferences-rename-shorthand-properties"]
- `lsp-typescript-preferences-rename-shorthand-properties`
____
Default value: `pass:[t]`

Enable/disable introducing aliases for object shorthand
properties during renames. Requires using TypeScript 3.4 or newer
in the workspace.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-update-imports-on-file-move-enabled"]
- `lsp-typescript-update-imports-on-file-move-enabled`
____
Default value: `pass:["prompt"]`

Enable/disable automatic updating of import paths when you
rename or move a file in VS Code. Requires using TypeScript 2.9
or newer in the workspace.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-update-imports-on-file-move-enabled"]
- `lsp-javascript-update-imports-on-file-move-enabled`
____
Default value: `pass:["prompt"]`

Prompt on each rename.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-auto-closing-tags"]
- `lsp-typescript-auto-closing-tags`
____
Default value: `pass:[t]`

Enable/disable automatic closing of JSX tags. Requires using
TypeScript 3.0 or newer in the workspace.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-auto-closing-tags"]
- `lsp-javascript-auto-closing-tags`
____
Default value: `pass:[t]`

Enable/disable automatic closing of JSX tags. Requires using
TypeScript 3.0 or newer in the workspace.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-javascript-suggest-enabled"]
- `lsp-javascript-suggest-enabled`
____
Default value: `pass:[t]`

Enabled/disable autocomplete suggestions.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-suggest-enabled"]
- `lsp-typescript-suggest-enabled`
____
Default value: `pass:[t]`

Enabled/disable autocomplete suggestions.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-typescript-surveys-enabled"]
- `lsp-typescript-surveys-enabled`
____
Default value: `pass:[t]`

Enabled/disable occasional surveys that help us improve VS
Code’s JavaScript and TypeScript support.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-vetur-server-command"]
- `lsp-vetur-server-command`
____
Default value: `pass:[("vls")
]`

Command to start vetur.

NOTE: Introduced in `lsp-mode` 6.1

____
