[id="lsp-solargraph-vars"]
==== `lsp-solargraph` settings

[id="lsp-solargraph-completion"]
- `lsp-solargraph-completion`
____
Default value: `pass:[t]`

Enable completion

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-solargraph-hover"]
- `lsp-solargraph-hover`
____
Default value: `pass:[t]`

Enable hover

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-solargraph-diagnostics"]
- `lsp-solargraph-diagnostics`
____
Default value: `pass:[t]`

Enable diagnostics

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-solargraph-autoformat"]
- `lsp-solargraph-autoformat`
____
Default value: `pass:[nil]`

Enable automatic formatting while typing (WARNING: experimental)

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-solargraph-formatting"]
- `lsp-solargraph-formatting`
____
Default value: `pass:[t]`

Enable document formatting

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-solargraph-symbols"]
- `lsp-solargraph-symbols`
____
Default value: `pass:[t]`

Enable symbols

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-solargraph-definitions"]
- `lsp-solargraph-definitions`
____
Default value: `pass:[t]`

Enable definitions (go to, etc.)

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-solargraph-rename"]
- `lsp-solargraph-rename`
____
Default value: `pass:[t]`

Enable symbol renaming

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-solargraph-references"]
- `lsp-solargraph-references`
____
Default value: `pass:[t]`

Enable finding references

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-solargraph-folding"]
- `lsp-solargraph-folding`
____
Default value: `pass:[t]`

Enable folding ranges

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-solargraph-log-level"]
- `lsp-solargraph-log-level`
____
Default value: `pass:["warn"]`

Level of debug info to log. ‘warn‘ is least and ‘debug‘ is most.

NOTE: Introduced in `lsp-mode` 6.1

____
