[id="lsp-html-vars"]
==== `lsp-html` settings

[id="lsp-html-experimental-custom-data"]
- `lsp-html-experimental-custom-data`
____
Default value: `pass:[nil]`

A list of JSON file paths that define custom tags, properties and other HTML
syntax constructs. Only workspace folder setting will be read.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-html-format-enable"]
- `lsp-html-format-enable`
____
Default value: `pass:[t]`

Enable/disable default HTML formatter.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-html-format-wrap-line-length"]
- `lsp-html-format-wrap-line-length`
____
Default value: `pass:[120]`

Maximum amount of characters per line (0 = disable).

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-html-format-unformatted"]
- `lsp-html-format-unformatted`
____
Default value: `pass:["wbr"]`

nil

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-html-format-content-unformatted"]
- `lsp-html-format-content-unformatted`
____
Default value: `pass:["pre,code,textarea"]`

nil

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-html-format-indent-inner-html"]
- `lsp-html-format-indent-inner-html`
____
Default value: `pass:[nil]`

nil

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-html-format-preserve-new-lines"]
- `lsp-html-format-preserve-new-lines`
____
Default value: `pass:[t]`

Controls whether existing line breaks before elements should be preserved.
Only works before elements, not inside tags or for text.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-html-format-max-preserve-new-lines"]
- `lsp-html-format-max-preserve-new-lines`
____
Default value: `pass:[nil]`

nil

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-html-format-indent-handlebars"]
- `lsp-html-format-indent-handlebars`
____
Default value: `pass:[nil]`

nil

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-html-format-end-with-newline"]
- `lsp-html-format-end-with-newline`
____
Default value: `pass:[nil]`

End with a newline.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-html-format-extra-liners"]
- `lsp-html-format-extra-liners`
____
Default value: `pass:["head, body, /html"]`

nil

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-html-format-wrap-attributes"]
- `lsp-html-format-wrap-attributes`
____
Default value: `pass:["auto"]`

Wrap attributes.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-html-suggest-html5"]
- `lsp-html-suggest-html5`
____
Default value: `pass:[t]`

Controls whether the built-in HTML language support suggests HTML5 tags,
properties and values.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-html-validate-scripts"]
- `lsp-html-validate-scripts`
____
Default value: `pass:[t]`

Controls whether the built-in HTML language support validates embedded
scripts.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-html-validate-styles"]
- `lsp-html-validate-styles`
____
Default value: `pass:[t]`

Controls whether the built-in HTML language support validates embedded
styles.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-html-auto-closing-tags"]
- `lsp-html-auto-closing-tags`
____
Default value: `pass:[t]`

Enable/disable autoclosing of HTML tags.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-html-trace-server"]
- `lsp-html-trace-server`
____
Default value: `pass:["off"]`

Traces the communication between VS Code and the HTML language server.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-html-server-command"]
- `lsp-html-server-command`
____
Default value: `pass:[("html-languageserver" "--stdio")
]`

Command to start html-languageserver.

NOTE: Introduced in `lsp-mode` 6.1

____
