[id="lsp-pyls-vars"]
==== `lsp-pyls` settings

[id="lsp-clients-python-library-directories"]
- `lsp-clients-python-library-directories`
____
Default value: `pass:[("/usr/")
]`

List of directories which will be considered to be libraries.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-server-command"]
- `lsp-pyls-server-command`
____
Default value: `pass:[("pyls")
]`

Command to start pyls.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-configuration-sources"]
- `lsp-pyls-configuration-sources`
____
Default value: `pass:[["pycodestyle"]
]`

List of configuration sources to use.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-jedi-completion-enabled"]
- `lsp-pyls-plugins-jedi-completion-enabled`
____
Default value: `pass:[t]`

Enable or disable the plugin.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-jedi-completion-include-params"]
- `lsp-pyls-plugins-jedi-completion-include-params`
____
Default value: `pass:[t]`

Auto-completes methods and classes with tabstops for each
parameter.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-jedi-definition-enabled"]
- `lsp-pyls-plugins-jedi-definition-enabled`
____
Default value: `pass:[t]`

Enable or disable the plugin.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-jedi-definition-follow-imports"]
- `lsp-pyls-plugins-jedi-definition-follow-imports`
____
Default value: `pass:[t]`

The goto call will follow imports.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-jedi-definition-follow-builtin-imports"]
- `lsp-pyls-plugins-jedi-definition-follow-builtin-imports`
____
Default value: `pass:[t]`

If follow_imports is True will decide if it follow builtin
imports.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-jedi-hover-enabled"]
- `lsp-pyls-plugins-jedi-hover-enabled`
____
Default value: `pass:[t]`

Enable or disable the plugin.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-jedi-references-enabled"]
- `lsp-pyls-plugins-jedi-references-enabled`
____
Default value: `pass:[t]`

Enable or disable the plugin.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-jedi-signature-help-enabled"]
- `lsp-pyls-plugins-jedi-signature-help-enabled`
____
Default value: `pass:[t]`

Enable or disable the plugin.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-jedi-symbols-enabled"]
- `lsp-pyls-plugins-jedi-symbols-enabled`
____
Default value: `pass:[t]`

Enable or disable the plugin.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-jedi-symbols-all-scopes"]
- `lsp-pyls-plugins-jedi-symbols-all-scopes`
____
Default value: `pass:[t]`

If True lists the names of all scopes instead of only the
module namespace.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-mccabe-enabled"]
- `lsp-pyls-plugins-mccabe-enabled`
____
Default value: `pass:[t]`

Enable or disable the plugin.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-mccabe-threshold"]
- `lsp-pyls-plugins-mccabe-threshold`
____
Default value: `pass:[15]`

The minimum threshold that triggers warnings about cyclomatic
complexity.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-preload-enabled"]
- `lsp-pyls-plugins-preload-enabled`
____
Default value: `pass:[t]`

Enable or disable the plugin.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-preload-modules"]
- `lsp-pyls-plugins-preload-modules`
____
Default value: `pass:[nil]`

List of modules to import on startup

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-pylint-enabled"]
- `lsp-pyls-plugins-pylint-enabled`
____
Default value: `pass:[t]`

Enable or disable the plugin.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-pycodestyle-enabled"]
- `lsp-pyls-plugins-pycodestyle-enabled`
____
Default value: `pass:[t]`

Enable or disable the plugin.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-pycodestyle-exclude"]
- `lsp-pyls-plugins-pycodestyle-exclude`
____
Default value: `pass:[nil]`

Exclude files or directories which match these patterns.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-pycodestyle-filename"]
- `lsp-pyls-plugins-pycodestyle-filename`
____
Default value: `pass:[nil]`

When parsing directories, only check filenames matching these
patterns.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-pycodestyle-select"]
- `lsp-pyls-plugins-pycodestyle-select`
____
Default value: `pass:[nil]`

Select errors and warnings

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-pycodestyle-ignore"]
- `lsp-pyls-plugins-pycodestyle-ignore`
____
Default value: `pass:[nil]`

Ignore errors and warnings

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-pycodestyle-hang-closing"]
- `lsp-pyls-plugins-pycodestyle-hang-closing`
____
Default value: `pass:[nil]`

Hang closing bracket instead of matching indentation of
opening bracket’s line.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-pycodestyle-max-line-length"]
- `lsp-pyls-plugins-pycodestyle-max-line-length`
____
Default value: `pass:[nil]`

Set maximum allowed line length.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-pydocstyle-enabled"]
- `lsp-pyls-plugins-pydocstyle-enabled`
____
Default value: `pass:[nil]`

Enable or disable the plugin.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-pydocstyle-convention"]
- `lsp-pyls-plugins-pydocstyle-convention`
____
Default value: `pass:[nil]`

Choose the basic list of checked errors by specifying an
existing convention.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-pydocstyle-add-ignore"]
- `lsp-pyls-plugins-pydocstyle-add-ignore`
____
Default value: `pass:[nil]`

Ignore errors and warnings in addition to the specified
convention.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-pydocstyle-add-select"]
- `lsp-pyls-plugins-pydocstyle-add-select`
____
Default value: `pass:[nil]`

Select errors and warnings in addition to the specified
convention.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-pydocstyle-ignore"]
- `lsp-pyls-plugins-pydocstyle-ignore`
____
Default value: `pass:[nil]`

Ignore errors and warnings

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-pydocstyle-select"]
- `lsp-pyls-plugins-pydocstyle-select`
____
Default value: `pass:[nil]`

Select errors and warnings

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-pydocstyle-match"]
- `lsp-pyls-plugins-pydocstyle-match`
____
Default value: `pass:["(?!test_).*\\.py"]`

Check only files that exactly match the given regular
expression; default is to match files that don’t start with
’test_’ but end with ’.py’.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-pydocstyle-match-dir"]
- `lsp-pyls-plugins-pydocstyle-match-dir`
____
Default value: `pass:["[^\\.].*"]`

Search only dirs that exactly match the given regular
expression; default is to match dirs which do not begin with a
dot.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-pyflakes-enabled"]
- `lsp-pyls-plugins-pyflakes-enabled`
____
Default value: `pass:[t]`

Enable or disable the plugin.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-rope-completion-enabled"]
- `lsp-pyls-plugins-rope-completion-enabled`
____
Default value: `pass:[t]`

Enable or disable the plugin.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-plugins-yapf-enabled"]
- `lsp-pyls-plugins-yapf-enabled`
____
Default value: `pass:[t]`

Enable or disable the plugin.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-rope-extension-modules"]
- `lsp-pyls-rope-extension-modules`
____
Default value: `pass:[nil]`

Builtin and c-extension modules that are allowed to be
imported and inspected by rope.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-pyls-rope-rope-folder"]
- `lsp-pyls-rope-rope-folder`
____
Default value: `pass:[nil]`

The name of the folder in which rope stores project
configurations and data. Pass ‘null‘ for not using such a folder
at all.

NOTE: Introduced in `lsp-mode` 6.1

____
