[id="lsp-intelephense-vars"]
==== `lsp-intelephense` settings

[id="lsp-intelephense-files-max-size"]
- `lsp-intelephense-files-max-size`
____
Default value: `pass:[1000000]`

Maximum file size in bytes.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-intelephense-files-associations"]
- `lsp-intelephense-files-associations`
____
Default value: `pass:[["*.php" "*.phtml"]
]`

Configure glob patterns to make files available for language
  server features.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-intelephense-files-exclude"]
- `lsp-intelephense-files-exclude`
____
Default value: `pass:[["**/.git/**" "**/.svn/**" "**/.hg/**" "**/CVS/**" "**/.DS_Store/**" "**/node_modules/**" "**/bower_components/**" "**/vendor/**/{Test,test,Tests,tests}/**"]
]`

Configure glob patterns to exclude certain files and folders from all language server features.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-intelephense-stubs"]
- `lsp-intelephense-stubs`
____
Default value: `pass:[["apache" "bcmath" "bz2" "calendar" "com_dotnet" "Core" "csprng" "ctype" "curl" "date" "dba" "dom" "enchant" "exif" "fileinfo" "filter" "fpm" "ftp" "gd" "hash" "iconv" "imap" "interbase" "intl" "json" "ldap" "libxml" "mbstring" "mcrypt" "mssql" "mysql" "mysqli" "oci8" "odcb" "openssl" "password" "pcntl" "pcre" "PDO" "pdo_ibm" "pdo_mysql" "pdo_pgsql" "pdo_sqlite" "pgsql" "Phar" "posix" "pspell" "readline" "recode" "Reflection" "regex" "session" "shmop" "SimpleXML" "snmp" "soap" "sockets" "sodium" "SPL" "sqlite3" "standard" "superglobals" "sybase" "sysvmsg" "sysvsem" "sysvshm" "tidy" "tokenizer" "wddx" "xml" "xmlreader" "xmlrpc" "xmlwriter" "Zend OPcache" "zip" "zlib"]
]`

Configure stub files for built in symbols and common
  extensions. The default setting includes PHP core and all
  bundled extensions.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-intelephense-completion-insert-use-declaration"]
- `lsp-intelephense-completion-insert-use-declaration`
____
Default value: `pass:[t]`

Use declarations will be automatically inserted for namespaced
  classes, traits, interfaces, functions, and constants.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-intelephense-completion-fully-qualify-global-constants-and-functions"]
- `lsp-intelephense-completion-fully-qualify-global-constants-and-functions`
____
Default value: `pass:[nil]`

Global namespace constants and functions will be fully
  qualified (prefixed with a backslash).

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-intelephense-format-enable"]
- `lsp-intelephense-format-enable`
____
Default value: `pass:[t]`

Enables formatting

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-intelephense-trace-server"]
- `lsp-intelephense-trace-server`
____
Default value: `pass:["off"]`

Traces the communication between VSCode and the intelephense
  language server.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-intelephense-storage-path"]
- `lsp-intelephense-storage-path`
____
Default value: `pass:["~/.emacs.d/lsp-cache"]`

Optional absolute path to storage dir.

NOTE: Introduced in `lsp-mode` 6.1

____
[id="lsp-intelephense-server-command"]
- `lsp-intelephense-server-command`
____
Default value: `pass:[("intelephense" "--stdio")
]`

Command to start Intelephense.

NOTE: Introduced in `lsp-mode` 6.1

____
